version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: wallet_management
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    restart: always
